### ISSUE TITLE
acmephp / core update

### ISSUE THREAD

**Issue by YannickHermans** [acmephp/acmephp#103]
Hiya,

I was planning on using the core class of acmephp for implementing Let's encrypt certificate handling seeing as it has lots of possibilities.
Now i noticed that it was version 1.0.0-beta4 using composer ([https://packagist.org/packages/acmephp/core](https://packagist.org/packages/acmephp/core)) while acmephp/acmephp includes version 1.0.0-beta5.

Once implemented i'll have to deploy it to different servers so it would be nice to just require the necessary core libraries with composer without needing the rest of the project.

Any chance you could bring this up-to-date? :-)

Thanks in advance!

Kind regards,

Yannick

**Comment by tgalopin** [comment]
Sorry for the delay answering !

I am planning to release a first stable (1.0.0) of all the components today :) .
