### ISSUE TITLE
php parse error

### ISSUE THREAD

**Issue by netvillage** [acmephp/acmephp#136]
ok, new to this, so I may not know what I am talking about. 
I got this to work on a win7 machine like a month ago, I used these commands to install it.
php -r "copy('https://acmephp.github.io/downloads/acmephp.phar', 'acmephp.phar');"
php -r "copy('https://acmephp.github.io/downloads/acmephp.phar.pubkey', 'acmephp.phar.pubkey');"
per the docs.
Version says 1.0.0-dev (note the dev)
Doing the same thing today on another win7 machine. After the install when trying to run the register command I get:
[26-Oct-2018 13:45:33 America/New_York] PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in phar://C:/LetsEncrypt/acmephp.phar/vendor/symfony/filesystem/Filesystem.php on line 727

I notice that the version is 1.0.0 (without the dev). I also note that the acmephp.phar are very different in size.

**Comment by tgalopin** [comment]
Hello @netvillage !

I indeed included a 4.0 version of Symfony Filesystem component. Let me build a new package :) .

**Comment by tgalopin** [comment]
I released 1.0.1 which should fix this issue as well as decrease the package size. Don't hesitate to ping me if needed :) !
