### ISSUE TITLE
DNS Token Incorrect

### ISSUE THREAD

**Issue by phlfvry** [acmephp/acmephp#144]
Using AcmePHP core, I'm pulling the token from the authorization challenge and using setting it as the value for TXT record.

I get this error:
`Challenge failed (response: {"type":"dns-01","status":"invalid","error":{"type":"urn:ietf:params:acme:error:unauthorized","detail":"Incorrect TXT record \"zM5RUN0TOPEc6Kk2xwaCDxWuVRp22eRSnQSUwGZXqZk\" found at _acme-challenge.mydomain.com","status":403},"url":"https:\/\/acme-staging-v02.api.letsencrypt.org\/acme\/challenge\/NFt4J2q4rjM38uTQyxlHvFTATeqBnPYR7P9ktPbMxKA\/201974209","token":"zM5RUN0TOPEc6Kk2xwaCDxWuVRp22eRSnQSUwGZXqZk"})`

The error message states that I input an incorrect TXT record, but it's exactly the same token retrieved from the challenge. I also tried using the token payload but that didn't work either.

**Comment by phlfvry** [comment]
Closing this because the token retrieved from the authorization is not the correct token to be used.

**Comment by Nevario** [comment]
Hi @pfcodes, I know you posted this a while ago but I'm stuck on the same issue...

How do i combine the token returned in the authorization challenge with the private key to generate the actual token TXT DNS record? Does Acme PHP have a built in method?

**Comment by pfcodes** [comment]
> Hi @pfcodes, I know you posted this a while ago but I'm stuck on the same issue...
> 
> How do i combine the token returned in the authorization challenge with the private key to generate the actual token TXT DNS record? Does Acme PHP have a built in method?

I want to say base64 encoding? Sorry I don't really remember and I regret not posting the answer.

**Comment by linushstge** [comment]
Maybe outdated, but anyone with the same question.
The TXT DNS Record has to be a base64Url + sha256 encoded string of your payload.

Acme PHP already provides an encoder to get the exact TXT record:

``` php
$extractor = new DnsDataExtractor();

$name = $extractor->getRecordName($challenge);
$value = $extractor->getRecordName($challenge);

// deploy your dns record (with your real dns backend, e.g.:)
$this->dnsService->createRecord($name, $value, 'TXT', 60);
```

Behind the scenes:

/core/Challenge/Dns/DnsDataExtractor.php:
``` php
    /**
     * Retrieves the value of the TXT record to register.
     */
    public function getRecordValue(AuthorizationChallenge $authorizationChallenge): string
    {
        return $this->encoder->encode(hash('sha256', $authorizationChallenge->getPayload(), true));
    }
```

RFC: https://datatracker.ietf.org/doc/html/rfc8555#section-8.4
