### ISSUE TITLE
Testing stuff and trying to revoke

### ISSUE THREAD

**Issue by netvillage** [acmephp/acmephp#150]
So I am experimenting with stuff, specifically replacing the step-by-step approach I used with your sweet RUN command (because of the expired authorization issue).
I created a certificate using 
  php acmephp.phar run config.yml
and all seemed good. Then I saw the cool --DELAY parameter which will let me set # days till the cert expires (I think), that should allow me to set it to 1 day and then I can see if my renewal code is all good.
  php acmephp.phar run --delay=1 config.yml
So I had already created the cert with the first command so it won't expire till Apr. I figured I could use the revoke to get rid of this one and I could create a new one that expires in a day. So I:
  php acmephp.phar revoke www.mydomain.com
and it says it worked!
But when I try to re-run RUN with a delay of 1 day. it says...
  Account registered successfully!
  Current certificate is valid until Thu, 25 Apr 2019 01:28:47 +0000, renewal is not necessary. Change --delay parameter to force renewal.

Did my revoke not really work?

**Comment by jderusse** [comment]
In fact, the option `delay` is about the remaining time to live of the certificate. Forcing a renewal would require `--delay=90`

When revoking a certificate, you're publishing the revocation through OCSP (https://letsencrypt.org/docs/revoking/). the certificate itself don"t change.

The client is basic and don"t check if a revocation has been published. It just read the certificate. Thta's why it's not application think the certificate is still valid.

We could improve this in 2 ways:
- The easy: deleting the certificate from the repository when the command "revoke" is called.
- The great: checking if the certificate has been revoking

Would be great to submit a PR if you have time
