### ISSUE TITLE
In Staging, this raises and 403 error causing an Exception

### ISSUE THREAD

**Issue by Hormah** [acmephp/acmephp#154]
When calling this method using the Staging url of LetEncrypt:
$acmeClient->requestCertificate();

On the this line: 
https://github.com/acmephp/acmephp/blob/b276743c62663e6bea5c983d076d455f79f43383/src/Core/AcmeClient.php#L235

An **Exception** is raised:
#0 C:\inetpub\wwwroot\ecommerce\modules\composer\vendor\acmephp\core\Http\ServerErrorHandler.php(102): AcmePhp\Core\Http\ServerErrorHandler->createDefaultExceptionForResponse(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), Object(GuzzleHttp\Exception\ClientException))
#1 C:\inetpub\wwwroot\ecommerce\modules\composer\vendor\acmephp\core\Http\SecureHttpClient.php(408): AcmePhp\Core\Http\ServerErrorHandler->createAcmeExceptionForResponse(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), Object(GuzzleHttp\Exception\ClientException))
#2 C:\inetpub\wwwroot\ecommerce\modules\composer\vendor\acmephp\core\Http\SecureHttpClient.php(288): AcmePhp\Core\Http\SecureHttpClient->handleClientException(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Exception\ClientException))
#3 C:\inetpub\wwwroot\ecommerce\modules\composer\vendor\acmephp\core\Http\SecureHttpClient.php(261): AcmePhp\Core\Http\SecureHttpClient->unsignedRequest('POST', 'https://acme-st...', Array, true)
#4 C:\inetpub\wwwroot\ecommerce\modules\composer\vendor\acmephp\core\AcmeClient.php(238): AcmePhp\Core\Http\SecureHttpClient->signedKidRequest('POST', 'https://acme-st...', 'https://acme-st...', Array)
#5 C:\inetpub\wwwroot\ecommerce\modules\composer\vendor\acmephp\core\AcmeClient.php(216): AcmePhp\Core\AcmeClient->finalizeOrder(Object(AcmePhp\Core\Protocol\CertificateOrder), Object(AcmePhp\Ssl\CertificateRequest), 180)
#6 C:\inetpub\wwwroot\ecommerce\control_panel\cli_certificate_auth.php(186): AcmePhp\Core\AcmeClient->requestCertificate('www.esolve.co.z...', Object(AcmePhp\Ssl\CertificateRequest))
#7 C:\inetpub\wwwroot\ecommerce\control_panel\cli_certificate_auth.php(312): processCertificate(Object(stdClass), Array, Object(AcmePhp\Core\Http\SecureHttpClient), true)
#8 {main}
A non-ACME 403 HTTP error occured on request "POST https://acme-staging-v02.api.letsencrypt.org/acme/finalize/7391638/27463925" (response body: " (truncated...)")

Debug Screenshot:
See the actual order, all the items are pending:
![Capture](https://user-images.githubusercontent.com/5639185/54620954-a1ed0080-4a6f-11e9-9d89-2d04fc71a489.JPG)

**And  a bit deeper, the client error reads:**
From SecureHTTPClient line 288:
"Client error: `POST https://acme-staging-v02.api.letsencrypt.org/acme/finalize/7391638/27465333` resulted in a `403 Forbidden` response:
{
  "type": "urn:ietf:params:acme:error:orderNotReady",
  "detail": "Order's status (\"pending\") is not acceptable for  (truncated...)
"

When running this in LIVE mode, the exact same request generates a certficate. I'm not sure if this is an LetsEncrypt issue, but there is clearly a difference between the live and staging environments.

**Comment by bfenton-smugmug** [comment]
I'm seeing this same issue. I think if this is a "known" failure mode (especially since `requestCertificate` has additional retry logic built in, I think this exception should be caught and discarded.

**Comment by bfenton-smugmug** [comment]
FWIW what we ended up doing is catching the `OrderNotReadyServerException` outside of the client, grabbing the authorizations from the Order, then looping through them and retrying the pending ones. It required deviating from the `requestCertificate` flow and manually creating & finalizing orders, but it got the job done.
