### ISSUE TITLE
Getting challenge failed (404) even when url is accesible through internet

### ISSUE THREAD

**Issue by danbulant** [acmephp/acmephp#155]
Hello.
I already have some active https on domains with acme, but recently, I accidentally run the check command before uploading the file, and from when I ran that, I always get authentication failed (file not found). When I try to read the file from another computer over internet, it works. Why? I think that's something with cache, because it always need some time to authenticate but now it immedietly say Challenge failed..

**Comment by danbulant** [comment]
![image](https://user-images.githubusercontent.com/30036876/54869444-9dd72080-4d98-11e9-8dbd-fc1b241b2abe.png)
This is screenshot of my server (I'm not directly on it). I'm not hiding IP adres because my webserver runs here so why

**Comment by tgalopin** [comment]
Maybe linked to https://github.com/acmephp/acmephp/issues/213, closing as it's old. If the problem still exists, ping me here!
