### ISSUE TITLE
Fullchain.pem file not generating

### ISSUE THREAD

**Issue by itslit-tech** [acmephp/acmephp#157]
On running the command to generate certificates for multiple domains, I see only key.public.pem and key.private.pem being created ? Should a fullchain.pem be also created so that I configure my webserver properly ? If yes, what wrong can I be doing ?

**Comment by tgalopin** [comment]
Hello,

In which directory are you finding these files? Are you looking in ~/.acmephp?

**Comment by itslit-tech** [comment]
Sorry, I was doing something wrong. Closing the issue.
