### ISSUE TITLE
Certificate file path for multiple domain certificates 

### ISSUE THREAD

**Issue by itslit-tech** [acmephp/acmephp#158]
On generating certificates for multiple domains A (the main domain) and B (another domain), what should be the path or the correct configuration of the SSL certificates in the apache config if the certificates have to be fetched for the domain B? 

I have set the paths in custom-http.conf as follows,
`SSLCertificateFile   path-to-certs/master/certs/A/public/fullchain.pem`
`SSLCertificateKeyFile   path-to-certs/master/certs/A/private/key.private.pem`.

The certificate is valid for https://{domainA} but on loading https://{domainB}, I get this error on the browser `This server could not prove that it is B; its security certificate is from A`. 

Do I need to load it off a separate `.conf` file / server blocks?

Thanks

**Comment by jderusse** [comment]
When you generate several certificate, 6ou need 1 ghost per certificate.
Otherwise you can create a single certificate for several domain, using SubjectAlternativeNames

**Comment by itslit-tech** [comment]
@jderusse Thanks a lot. It worked

**Comment by itslit-tech** [comment]
@jderusse Hi, another issue I faced with this is, in case the SSL Certificate exists for domain A, I get the following error when generating the SSL certificate for domain B  -> `cURL error 51: SSL: no alternative certificate subject name matches target host name {domain B}`.  

The certificates work fine when I generate them using the below .yml for both the domains set initially. But on generating the certificate for domain A first as the main domain and later on, for both domain A and B with B as the `subject alternative name`, I get the above-mentioned error. Any help will be greatly appreciated.

The .yml file in both the cases is as follows - 

```
certificates:
    - { domain: A subject_alternative_names: [B] }

```
