### ISSUE TITLE
Renewal issues - The order has not been validated

### ISSUE THREAD

**Issue by bpolaszek** [acmephp/acmephp#159]
Hello there,

I've been using AcmePHP from almost the beginning and I still have issues in renewing certificates.

For example, on February 26 I requested a certificate for a domain and 2 sub-domains and they are to be renewed on May 27. However, the automatic renewal systematically fails with the following message:

> The order has not been validated.

I've got the exact same issue on another domain, for another project on another server. 

I'm using AcmePHP 1.1. Is it really production ready? I'd really love to debug things by myself but this implies a strong knowledge of how Let's encrypt and certificates work, which I can't pretend I have.

Every time, I have to authorize / check / request each domain by myself, so that's something I can't automate and needs to be done every 3 months...

Thank you,
Ben

**Comment by jderusse** [comment]
Did you try the `run` command ? This one should take care of re-newing challenges

**Comment by bpolaszek** [comment]
@jderusse Not yet, I usually go to https://acmephp.github.io/ where it's not documented yet. I'll give it a try. Thanks!
