### ISSUE TITLE
The "request" command always fails

### ISSUE THREAD

**Issue by aik099** [acmephp/acmephp#160]
The "request" command returns this error:

```
In AcmeClient.php line 247:
                                                                           
  Certificate request failed (response: The order has not been validated)  
                                                                           
```

Worked 3 months ago, when I was renewing a certificate.

**Comment by bpolaszek** [comment]
Hi @aik099, 

I think the `request` command is kinda deprecated and the documentation is not up-to-date. With the `run` command, you can define automatisms to generate challenges, expose them, check them and renew your certificates automatically. I hade the same issue with #159.

Some more information can be found [here](https://github.com/acmephp/acmephp#run-command)

Don't hesitate if you need some help.

**Comment by bpolaszek** [comment]
@tgalopin @jderusse I know this package is not part of the Symfony ecosystem, but I do think opening a Slack channel on Symfony devs would really help. What do you think?

**Comment by aik099** [comment]
> Hi @aik099,
> 
> I think the `request` command is kinda deprecated and the documentation is not up-to-date. With the `run` command, you can define automatisms to generate challenges, expose them, check them and renew your certificates automatically. I hade the same issue with #159.
> 
> Some more information can be found [here](https://github.com/acmephp/acmephp#run-command)
> 
> Don't hesitate if you need some help.

That's a move in the right direction, because running 3 commands each 3 months for every sub-domain I need and manually creating all these challenge files is really painful a process. Spent 1h in attempts to renew expired certificate.

That configuration file format seems to be pretty complex (even for me being a developer 10+ years).

Could you please write an example configuration file for my setup:

1. I have 2 domains: domain1.com and sub-domain.domain1.com
2. I have DocumentRoot (where `.well-known` folder is) under `/home/username/web` folder
3. the `.acmephp` folder is located under `/home/username` folder

It would be really great if somehow I would be able to put ACME challenges for both domains in DNS so that renewing a certificate won't require connecting back to my domain at 80 port.

Thanks.

**Comment by jderusse** [comment]
Created PR https://github.com/acmephp/documentation/pull/16 and https://github.com/acmephp/acmephp/pull/161 to deprecate old commands.

You'll find a sample of config in https://acmephp.github.io/documentation/getting-started/2-obtain-certificate-easy.html you can play with solver's adapter = local

**Comment by tgalopin** [comment]
Closing this as 2.0 will only have the run command
