### ISSUE TITLE
The rightful autoloader entry is bothering me.

### ISSUE THREAD

**Issue by xiaohuilam** [acmephp/acmephp#167]
https://github.com/acmephp/acmephp/blob/9203dec902f2d44cc248ba94d7417ef3ecd0d7c0/bin/acme#L28-L32

I am installing acmephp globally, to `~/.composer/vendor/acmephp/acmephp/`, and i debug and develope in same folder, so i composer `installed` all the packages into `~/.composer/vendor/acmephp/acmephp/vendor/`.

When i required a new package, my old `~/.composer/vendor/`doesn't contain, but `~/.composer/vendor/acmephp/acmephp/vendor/` contains, the `bin/acme` can't load it!

I think the 
```php
     __DIR__.'/../../../autoload.php',
```
should be placed after 
```php
     __DIR__.'/../vendor/autoload.php', 
```

**Comment by SamMousa** [comment]
Closing this due to old age.
