### ISSUE TITLE
Nothing created in C:\Users\Administrator\.acmephp\master\certs

### ISSUE THREAD

**Issue by netvillage** [acmephp/acmephp#172]
So I'm running the command
php acmephp.phar run configpp.yml
(its ver 1.1.1)

which gives me
Registering contact sysop@netvillage.com...
Loading account key pair...
Registering on the ACME server...
Account registered successfully!
Loading account key pair...
Requesting certificate order...
Solving challenge for domain ... etc...

but it never creates cert folders and stuff under master\certs\
Earlier in the day I was able to do it just fine with another website (I was creating a batch file to automate stuff), and the only change I made was domain name. Is there some option I can set to test? Any particular reason it might not create the proper stuff?

**Comment by netvillage** [comment]
ok, could this be a rate limit? I noticed my automated process ran last night and it seemed to create the folder this time. Is there a switch I can use for testing?

**Comment by tgalopin** [comment]
You can use the staging environment: 

```
php acmephp.phar --server=https://acme-staging-v02.api.letsencrypt.org/directory
```
