### ISSUE TITLE
The commonName assert is conflict with some CA product's csr demand

### ISSUE THREAD

**Issue by xiaohuilam** [acmephp/acmephp#175]
https://github.com/acmephp/acmephp/blob/6b65f1ae33f530cbb65c648a9c4e8846a1df1bf0/src/Ssl/DistinguishedName.php#L67

**Comodo's some IP product requires common name leave blank**
[How To Generate CSR without Common name](https://www.gogetssl.com/wiki/csr-generation/generate-csr-without-cn/)

**Comment by tgalopin** [comment]
I'm pretty sure they ask to enter `KEEP EMPTY`, not to actually leave it empty, or do they?
