### ISSUE TITLE
Changing --delay parameter doesn't force renewal

### ISSUE THREAD

**Issue by AeonFr** [acmephp/acmephp#176]
Running `acmephp run config.yml` has the following output:

```
Registering contact xxxx@xxxx.com
Loading account key pair...
Registering on the ACME server...
Account registered successfully!
Current certificate is valid until Wed, 25 Dec 2019 07:36:36 +0000, renewal is not necessary.
Change --delay parameter to force renewal.
Installing certificate for domain XXX.net...
```

As far as I understand, I don't need to renew the certificate until Christmas, *but I can* if I want to. 

```
...renewal is not necessary.
Change --delay parameter to force renewal.
```

Yet, using the following commands have no effect:

```
acmephp run --delay=1 config.yml
acmephp run --delay 1 config.yml
acmephp run -d=1 config-yml
acmephp run -d 1 config.yml
acmephp run config.yml --delay=1
acmephp run config.yml --delay 1
```

In definite, the delay parameter is setted (there's no error and the command runs), but the output doesn't change.

```
C:\https> php --version
PHP 5.6.40 (cli) (built: Jan  9 2019 15:10:36)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

C:\https> php acmephp.phar --version
Acme PHP - Let's Encrypt client 1.1.1
```

I'm able to renew using the step-by-step alternative: using `authorize`, `check` and `renew --force`. But `run` isn't doing the trick.

**Comment by jderusse** [comment]
IIRC `1` meaning wait until the certificate expires in 1 days before renewing it.

Have a try to `-d 90`

**Comment by AeonFr** [comment]
Oh! I was getting it all wrong. I understand now why it didn't work...
Thanks!
