### ISSUE TITLE
Multiple Domains in one certificate

### ISSUE THREAD

**Issue by shyim** [acmephp/acmephp#18]
On my ISP Panel i have only one input for the domain without www and with www. Can i request two domains in one certificate (www.example.com, example.com)?

**Comment by tgalopin** [comment]
It's technically possible indeed. Let's Encrypt supports [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication) and therefore is able to provide multiple domains certificates.

However for the moment it's not possible to request such certificates using the Acme PHP CLI client. That's something I plan to add before the first beta and it should be quite soon (the monitoring system I was working on for the moment is almost ready).

In the meantime, if you are in a hurry, I recommand you either to create a small PHP script and use the Acme PHP Core library to request your certificate (that's not difficult, if you need a hand don't hesitate) or to use the official Let's Encrypt client: https://certbot.eff.org.

**Comment by tgalopin** [comment]
Working on it: https://github.com/acmephp/acmephp/pull/20

**Comment by tgalopin** [comment]
This has been fixed by https://github.com/acmephp/acmephp/pull/24 and will be released in the next version (beta1).

**Comment by tgalopin** [comment]
Released in beta1: https://github.com/acmephp/acmephp/releases/tag/1.0.0-beta1. Run `php acmephp.phar self-update` to update.
