### ISSUE TITLE
Subject alternative name causes unexpected 403 response

### ISSUE THREAD

**Issue by pauladams8** [acmephp/acmephp#181]
When I pass an array of subject alternative names when requesting a certificate (as pass of the certificate request object), the ACME API returns an unrecognised 403 response.
The error is as follows: `AcmePhp/Core/Exception/AcmeCoreServerException with message 'A non-ACME 403 HTTP error occured on request "POST https://acme-v02.api.letsencrypt.org/acme/finalize/(redacted)/(redacted)" (response body: " (truncated...)")'`.

Unfortunately, I am unable to read the actual error message as the client limits it to 120 characters and there is no way to retrieve the underlying Guzzle client instance, as far as I could see.

**Comment by pauladams8** [comment]
After setting the `lastResponse` property to public, I got the error. The message is `Order's status ("pending") is not acceptable for finalization`.

Perhaps this could be registered as an exception for easier debugging?

**Comment by pauladams8** [comment]
I'm guessing this is because you need to authorize the other names separately (in my case the name is just a www subdomain so I didn't realise this would need separate DNS authorization).

Think I've resolved this myself, but it would still be helpful to add the `orderNotReady` type to the exception mappings in `ServerErrorHandler`.

**Comment by jderusse** [comment]
yes, you need an authorization for each domain.

see how the command `run` works
