### ISSUE TITLE
The client lacks sufficient authorization: User account ID doesn't match account ID in authorization

### ISSUE THREAD

**Issue by gkarugi** [acmephp/acmephp#187]
I am having a problem verifying the dns-01 challenge. I am getting the following error
`The client lacks sufficient authorization: User account ID doesn't match account ID in authorization`

When does the UnauthorizedServerException get thrown? because all my google searches reference to the http-01 challenge for a fix.

**Comment by tgalopin** [comment]
Are you using the same account (`acmephp register`) than the one you are using to do the challenge?

**Comment by SamMousa** [comment]
Closing this due to old age.
