### ISSUE TITLE
A non-ACME 400 HTTP error occured on request

### ISSUE THREAD

**Issue by kalada** [acmephp/acmephp#194]
Attempting to integrate the acmephp library into my project, but I keep getting this error

> "A non-ACME 400 HTTP error occured on request "POST https://acme-v02.api.letsencrypt.org/acme/new-order" (response body: " (truncated...)")"

Here's the client initialization code
`      
       public static function getClient()
       {
            $secureHttpClientFactory = new SecureHttpClientFactory(
             new GuzzleHttpClient(),
            new Base64SafeEncoder(),
            new KeyParser(),
            new DataSigner(),
            new ServerErrorHandler()
        );

        $acmeKeyPath = storage_path('acme-keys');
        if (!file_exists($acmeKeyPath)) {
            mkdir($acmeKeyPath, 0700, true);
        }

        $publicKeyPath = $acmeKeyPath . '/account.pub.pem';
        $privateKeyPath = $acmeKeyPath . '/account.pem';

        if (!file_exists($privateKeyPath)) {
            $keyPairGenerator = new KeyPairGenerator();
            $keyPair = $keyPairGenerator->generateKeyPair();

            file_put_contents($publicKeyPath, $keyPair->getPublicKey()->getPEM());
            file_put_contents($privateKeyPath, $keyPair->getPrivateKey()->getPEM());
        } else {
            $publicKey = new PublicKey(file_get_contents($publicKeyPath));
            $privateKey = new PrivateKey(file_get_contents($privateKeyPath));

            $keyPair = new KeyPair($publicKey, $privateKey);
        }

        $secureHttpClient = $secureHttpClientFactory->createSecureHttpClient($keyPair);
        $acmeClient = new AcmeClient($secureHttpClient, 'https://acme-v02.api.letsencrypt.org/directory');

        return $acmeClient;
    }`

and the code to request authorization of the domain

`$registerResponse = $this->acmeClient->registerAccount(null, 'myemail@gmail.com');
$authorizationChallenges = $this->acmeClient->requestAuthorization('http://staging-domain.nll/');
dd($authorizationChallenges);`

any ideas what I could be doing wrong?

**Comment by SamMousa** [comment]
Closing this due to old age.
