### ISSUE TITLE
can't make wildcard cert.

### ISSUE THREAD

**Issue by bonnedav** [acmephp/acmephp#200]
I just get `Impossible to create the root directory "C:/Users/TheD_/.acmephp/backup\var/*.davidb.tk".` when I try to do `php acmephp.phar authorize -s DNS *.[domain]`.

**Comment by karjanme** [comment]
I was able to create a wildcard certificate today. I ran the authorize command with both the domain and the wildcard.

```
> php acmephp.phar --version
Acme PHP - Let's Encrypt client 1.0.1
> php acmephp.phar authorize [domain] *.[domain] -s dns
```
