### ISSUE TITLE
Installing certificate error

### ISSUE THREAD

**Issue by arthurbass** [acmephp/acmephp#205]
In InstanceProfileProvider.php line 240:
                                                                                                                             
  Error retrieving credentials from the instance profile metadata server. (cURL error 28: Connection timed out after 1001 m  
  illiseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html))

**Comment by arthurbass** [comment]
am I doing something wrong?

Testing the challenge for domain MYDOMAIN.COM...
Requesting authorization check for domain MYDOMAIN.COM...
Testing the challenge for domain www.MYDOMAIN.COM...
Requesting authorization check for domain www.MYDOMAIN.COM...
Cleaning up challenge for domain MYDOMAIN.COM...
You can now cleanup your DNS by removing the domain _acme-challenge._acme-challenge.MYDOMAIN.COM..
Cleaning up challenge for domain www.MYDOMAIN.COM...
You can now cleanup your DNS by removing the domain _acme-challenge._acme-challenge.www.MYDOMAIN.COM..
Requesting certificate for domain MYDOMAIN.COM...
Loading account key pair...  
Certificate requested successfully!
Installing certificate for domain MYDOMAIN.COM...

In InstanceProfileProvider.php line 240:
                                                                                                                             
  Error retrieving credentials from the instance profile metadata server. (cURL error 28: Connection timed out after 1001 m  
  illiseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html))

**Comment by tgalopin** [comment]
Hello!

Are you using an AWS storage behind AcmePHP?
