### ISSUE TITLE
Deprecated commands in documentation

### ISSUE THREAD

**Issue by DevyV** [acmephp/acmephp#221]
Your documentation is really too old now here: https://acmephp.github.io/documentation/
Firstly, following the docs, you will install a really old version (1.0.1).

Should you figure out how to install the latest version (not a big job but takes extra time and efforts), then again for almost all commands your docs advice you will receive:

"This command is deprecated. Use command "run" instead"

Yet there is not any detailed documentation how to use the new 'run' command (just an example for those who can access their webserver's filesystem - I actually need to create certificates for an appliance where I can just import it through Web GUI).

So I actaully would like to simply migrate these commands 1-by-1 separately to the new 'run' command OR create a config file that combines all of these and can be used with the 'run' command, but I do not know how I could do that:

php acmephp.phar register youremail@example.com
php acmephp.phar authorize yourdomain.org
php acmephp.phar check yourdomain.org
php acmephp.phar request yourdomain.org -a www.yourdomain.org -a anotherdomain.org

**Comment by tgalopin** [comment]
Hi!

Yes, I plan to work on the documentation when I can. You can find an example on https://github.com/acmephp/acmephp#run-command and feel free to ask me here if you have question.

**Comment by DevyV** [comment]
Hi!

Unfortunately, the documentation has still not been updated since 2020 (2 years!). I still do not know how to RENEW certificates with the `run` command.

Could you specify the very exact way to **RENEW** 2 certificates with the 'run' command, please?

This is the deprecated command I wanted to use:
`php acmephp.phar request yourdomain.org -a www.yourdomain.org -a anotherdomain.org`
(Note: I posted the details in here: https://github.com/acmephp/documentation/issues/23#issue-1154995648)

What should it be migrated to?

**Comment by SamMousa** [comment]
Closing this due to old age.
