### ISSUE TITLE
Manual renewal does not work

### ISSUE THREAD

**Issue by DevyV** [acmephp/acmephp#222]
Renewal status says:
**Needs renewal? Yes**

Manual renewal just does not work with:
**php acmephp.phar request yourdomain.org -a www.yourdomain.org -a anotherdomain.org**

It always reports:
**[malformed] The request message was malformed: No order for ID xxxxxxxxxxxxxxxxxxx**

If I run:
**php acmephp.phar check -s dns yourdomain.org**

then I receive:
**[malformed] The request message was malformed: Expired authorization**

So I need to start from the beginning again:
1. php acmephp.phar authorize yourdomain.org
2. php acmephp.phar check yourdomain.org
3. php acmephp.phar request yourdomain.org -a www.yourdomain.org -a anotherdomain.org

**Comment by tgalopin** [comment]
Hi @DevyV !

Could you try to migrate to the run command? It would probably work better: https://github.com/acmephp/acmephp#run-command

**Comment by DevyV** [comment]
Hi @tgalopin,

I am quite a beginner and just cannot figure out what a proper config filw would be for my case:
I have 2 domains I wish to manage the certificate for (e.g. domain-a.com & domain-b.com).
As a result, I wish to save the certificate into a directory only because I will manually need to upload it to an appliance.

I already created the certificate with DNS challenge (as I need the certificate for an appliance where I can install it manually only, I cannot access filesystem of the appliance at all):

**php acmephp.phar authorize --solver dns *.domain-a.com *.domain-b.com
php acmephp.phar check -s dns *.domain-a.com *.domain-b.com
php acmephp.phar request *.domain-a.com *.domain-b.com**

The above resulted in my certificate saved in a directory:

**/home/myself/.acmephp/master/certs/*.domain-a.com**

But as I said before, renewal is not working with:

**php acmephp.phar request *.domain-a.com -a *.domain-b.com**

I would like to renew the existing certificate without the need to bother with new domain checking procedures. Just simply request a renewed certificate.

Could you advice what my config file should be exactly to use it with the "run" command to renew my existing certificate so that the new certificate would also be stored in the same (or a new) dircetory, please?

Many thanks in advance!

**Comment by SamMousa** [comment]
Closing this due to old age.
