### ISSUE TITLE
Mutilple Domains in the PHP Library - AcmeClient & AcmeClientInterface

### ISSUE THREAD

**Issue by Hormah** [acmephp/acmephp#226]
I have scoured the Internet to find if someone has this same issue. 

I have two domains somedome.co.za and www.somedomain.co.za that should be secured via LetEncrypt Cert. I see from the various posts that the command line version deals with this but our software uses the library. 

Making simple change to AcmeClient allow for mutiple Autentication request and then adding the subjectAlternativeNames in DistinguishedName nicely.

Can you consider making the change to allow Multiple Domain Enrollment.

**Comment by tgalopin** [comment]
I'm not sure what you have in mind but anything that's feasible with the CLI is feasible with the library, as the CLI only uses the library. You can request multiple domains for a same certificate using a distinguished name that includes alternative subjects (https://github.com/acmephp/acmephp/blob/master/src/Ssl/DistinguishedName.php).

**Comment by Hormah** [comment]
Unless I am missing something in how the process works, you need to request an auth for the domain and for the sub-domain. So, as a convenience. Domains array will then contain ['somedomain.co.za', 'www.somedomain.co.za']:

After line 193, add function:

    public function requestMultipleAuthorization(array $domains): array 
    {
        Assert::allStringNotEmpty($domains, 'requestMultipleAuthorization::$domains expected a list of strings. Got: %s');

        if (is_array($domains)) {
            $order = $this->requestOrder($domains);

            $authorizationChallenges = array();

            try {
                foreach($domains as $domain) {
                    $authorizationChallenges[] = $order->getAuthorizationChallenges($domain);
                }
                return $authorizationChallenges;
            } catch (AcmeCoreClientException $e) {
                throw new ChallengeNotSupportedException();
            }
        }
    }

**Comment by tgalopin** [comment]
Ah right, you do need to request multiple authorizations. If you want to open a PR to add this helper function, I'd be glad to review it!

**Comment by SamMousa** [comment]
Closing this due to old age.
