### ISSUE TITLE
acmephp/core v2 requires acmephp/core v1

### ISSUE THREAD

**Issue by ziemkowski** [acmephp/acmephp#229]
When upgrading both libraries to v2, `acmephp/core` complains that it requires `acmephp/ssl` v1.

An app integrating directly to the core and ssl libraries should be able to use only the v2 releases of both libraries.

**Comment by tgalopin** [comment]
Ah, indeed, let me fix that :)

**Comment by tgalopin** [comment]
I just released 2.0.1 which should fix this problem.
