### ISSUE TITLE
How to use LibDNS?

### ISSUE THREAD

**Issue by aik099** [acmephp/acmephp#235]
While looking at the code I've found this line:

https://github.com/acmephp/acmephp/blob/2e43e838c0cc5b28a7d6f22d8b0a2e986e6a8369/src/Cli/Command/AbstractCommand.php#L130

It suggests that LibDNS is automatically used, when available, however, how can I make it available inside the `acmephp.phar`, that I've downloaded?

I've tried cloning this project's repo and doing `composer require daverandom/libdns`, but that ended up in the error:

```
  Problem 1
    - The requested package phpspec/prophecy (locked at 1.8.0, required as ^1.9) is satisfiable by phpspec/prophecy[1.8.0] but these conflict with your requirements or minimum-stability.
  Problem 2
    - The requested package symfony/phpunit-bridge (locked at v4.2.5, required as ^5.0) is satisfiable by symfony/phpunit-bridge[v4.2.5] but these conflict with your requirements or minimum-stability.
```

Not being able to install a library because of dev dependencies that's something new :(

**Comment by SamMousa** [comment]
Closing this due to old age.

**Comment by aik099** [comment]
@SamMousa , was the problem solved?

**Comment by SamMousa** [comment]
No, im closing it due to old age

**Comment by aik099** [comment]
So you're closing a bug report because it wasn't fixed by anyone for a long time. OK.
