### ISSUE TITLE
build instructions or jwt problem

### ISSUE THREAD

**Issue by bobmagicii** [acmephp/acmephp#236]
first i saw in the log that 2.0.1 had some jwt updates so i was like maybe it will fix this problem *only one* of my domains is having. the tagged 2.0.0 release has no phar, the box.conf is still .dist, and my vague low effort attempt to build a phar by renaming box.conf and yelling at my console did not yield results.

```
Solving challenge for domain [...]
Testing the challenge for domain [...]
```

it spends forever on this stage above. then eventually times out with the following.

```
Can not self validate challenge for domain [...]. Maybe letsencrypt will be able to do it...
Requesting authorization check for domain [...]...

 [badNonce] The client sent an unacceptable anti-replay nonce: JWS has an invalid anti-replay nonce: "0003ud2LbafF4jAWV1BNwA8PcMVi9HylVkcorQ4gG6b3F  
  MI" (on request "POST https://acme-v02.api.letsencrypt.org/acme/chall-v3/13824968411/5_TCEA")
```

**Comment by SamMousa** [comment]
Closing this due to old age.
