### ISSUE TITLE
Invalid Accept header for "get certificate" request - breaks with BuyPass

### ISSUE THREAD

**Issue by Grendel7** [acmephp/acmephp#238]
I'm having an issue using AcmePHP (and specifically AcmePHP/Core) with the Acme server from BuyPass: https://community.buypass.com/t/k9r5cx/get-started

The issue occurs when the "get certificate" part. The [RFC section 7.4.2](https://datatracker.ietf.org/doc/html/rfc8555#section-7.4.2) states that the desired certificate format can be specified with the Accept header, and the default being `application/pem-certificate-chain`.

But AcmePHP indiscriminately sets a return type `application/json,application/jose+json,`. Let's Encrypt just ignores that and gives you a certificate in the default format. But BuyPass's server implementation checks this and detects that it cannot provide a certificate in the desired format, so it returns a `HTTP 406 Not Acceptable` error.

BuyPass confirms this is the issue on their own forum: https://community.buypass.com/t/x2h3x97?r=60h3m0k

One quick and dirty solution to this is to just add the `application/pem-certificate-chain` return type to all requests. A quick test against BuyPass doesn't indicate any issues there. Although differentiating the Accept header depending on the resource being requested would be even better.

**Comment by Blackbam** [comment]
Should be fixed, thank you for the PR.
