### ISSUE TITLE
PHP8 compatability

### ISSUE THREAD

**Issue by roelvanduijnhoven** [acmephp/acmephp#240]
I cannot get this package to run on PHP 8.0, and I could not find an issue on this topic yet. 

I opened https://github.com/acmephp/acmephp/pull/239 to add PHP8 to the workflow. So we can see what needs to happen to make this happen.

Note: the fix in https://github.com/acmephp/acmephp/pull/231 is necessary at the minimum. But that fix is not released yet. 

---

And thanks for this awesome package! It helps us to create and maintain almost ~100.000 certificates! :pray:

**Comment by roelvanduijnhoven** [comment]
Unrelated: I feel we can better change the constraint in composer.json from `>=7.2.5` to `"~7.2.5 || ~8"`. That way it is more explicit that this package supports PHP8. I more agree; I'd be happy to provide a patch.

**Comment by splitice** [comment]
Can we get a release so https://github.com/acmephp/acmephp/commit/192872c085f9865f2cd90db6556acf7d13591eda can go out? PHP8 is hardly new at this point.

**Comment by tgalopin** [comment]
Yes, I'll do that asap :)

**Comment by splitice** [comment]
@tgalopin hows it coming?

**Comment by mn7zDev** [comment]
@tgalopin , any news?

**Comment by tgalopin** [comment]
This should be done in 2.1:

https://github.com/acmephp/acmephp/releases/tag/2.1.0

**Comment by mn7zDev** [comment]
It is not fixed yet, I can see acmephp still using abandoned library which is conflicting with the PHP8 version

https://github.com/acmephp/acmephp/blob/master/composer.json#L54
https://github.com/humbug/phar-updater/blob/master/composer.json#L15
