### ISSUE TITLE
Error in KeyPairGenerator.php on registering with Let's Encrypt

### ISSUE THREAD

**Issue by ghost** [acmephp/acmephp#244]
When attempting to register my account key in Let's Encrypt with

`php acmephp.phar register myemail@example.org`

I get the following error:
```
In KeyPairGenerator.php line 48:
  OpenSSL key creation failed during generation with error: error:0909006C:PEM routines:get_name:no start l
  ine
```
No sure if I'm doing anything wrong. I'm on a Windows 10 machine.

**Comment by SamMousa** [comment]
Closing this due to old age.
