### ISSUE TITLE
Public Support for RSA Key Size Configuration

### ISSUE THREAD

**Issue by iricketson** [acmephp/acmephp#247]
It looks like acmephp [has internal support for configuring the RSA key size](https://github.com/acmephp/acmephp/blob/2e43e838c0cc5b28a7d6f22d8b0a2e986e6a8369/src/Ssl/Generator/RsaKey/RsaKeyOption.php#L21) (e.g. 2048 vs 4096), however [it doesn't appear there is a way to define this configuration](https://github.com/acmephp/acmephp/blob/2e43e838c0cc5b28a7d6f22d8b0a2e986e6a8369/src/Cli/Command/Helper/KeyOptionCommandTrait.php#L26) when using the tool.  More specifically, [the CLI tool doesn't accept bit size configuration](https://github.com/acmephp/acmephp/blob/2e43e838c0cc5b28a7d6f22d8b0a2e986e6a8369/src/Cli/Command/RunCommand.php#L82).

Am I missing something here, or is this not possible in its current state?

**Comment by programster** [comment]
I just hit this issue, noticing that I am generating 4096 bit keys, but AWS will only work with 2048 bit keys for a lot of their services. It would be really good to be able to specify the key size in the configuration.

**Comment by SamMousa** [comment]
Closing this due to old age.
