### ISSUE TITLE
padraic/phar-updater is abandoned

### ISSUE THREAD

**Issue by W0rma** [acmephp/acmephp#253]
[`AcmePhp\Cli\Command\SelfUpdateCommand`](https://github.com/acmephp/acmephp/blob/master/src/Cli/Command/SelfUpdateCommand.php) uses features of the abandoned package [`padraic/phar-updater`](https://github.com/humbug/phar-updater).

I'm not sure about a proper replacement. 
https://github.com/consolidation/self-update seems to have similar features.

**Comment by Man7asP** [comment]
Hi, any updates on this?

**Comment by Blackbam** [comment]
@Man7asP Would be glad about any PR on this, I can check myself if I find some time.

**Comment by Man7asP** [comment]
@Blackbam , can I get your contacts to discuss it?

**Comment by Blackbam** [comment]
@Man7asP All on my GitHub profile page ;)
