### ISSUE TITLE
Documentation missing? Change ACME service

### ISSUE THREAD

**Issue by xsrf** [acmephp/acmephp#255]
Hey,
I may have missed the obvious, but is there any documentation besides examples?

The landing page https://acmephp.github.io/ tells me there are at least four command line arguments:
```
# Register your account key in Let's Encrypt
$ php acmephp.phar register myemail@example.org

# Prove you own the domain "mydomain.com"
$ php acmephp.phar authorize mydomain.com

# Ask the server to check your proof
$ php acmephp.phar check mydomain.com

# Get the certificate!
$ php acmephp.phar request mydomain.com
```
On the other hand `php acmephp.phar --help` tells me that `php acmephp.phar list` would list all commands, but it lists:
```
Available commands:
  help         Displays help for a command
  list         Lists commands
  revoke       Revoke a SSL certificate for a domain
  run          Automatically challenge domains and request certificates configured in the given file
  self-update  Update acmephp.phar to most recent stable, pre-release or development build.
  status       List all the certificates handled by Acme PHP
```
There is no mention of the above commands... And it looks like they don't work (version mismatch?!).

Well okay, https://acmephp.github.io/documentation/getting-started/2-obtain-certificate-easy.html tells me I should use `php acmephp.phar run config.yml` with a config-file. The example config-file is also in the readme. But other than this I cannot find any documentation what keys and values I can use in the config file, how it should be structured and what the keys/values actually do.
Is this all what is available, or did I miss something?

My basic questions are:
- How do I set the ACME provider used? I don't want to use LetsEncrypt, I'd like to use `https://acme.sectigo.com/v2/DV` instead
- How do I set the destination for the http challenge file? document root is on the local filesysem, I don't need ftp

Thx

**Comment by SamMousa** [comment]
Closing this due to old age.
