### ISSUE TITLE
Staging environment?

### ISSUE THREAD

**Issue by code-a-cola** [acmephp/acmephp#258]
Is there an ability to use letsencrypt's staging environment for testing? It sure would come in handy with testing and not reaching limit caps.

**Comment by xywf221** [comment]
CLI does not support custom CA server.If you want to add another CA server, try editing it https://github.com/acmephp/acmephp/blob/master/src/Cli/Application.php#L28

**Comment by smashi** [comment]
you can use https://acme-staging-v02.api.letsencrypt.org/directory for testing

**Comment by SamMousa** [comment]
Closing this due to old age.
