### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by SamMousa** [acmephp/acmephp#272]
Looking at issues and PRs, and at the graphs in GH Insights:
![image](https://github.com/acmephp/acmephp/assets/547021/ef3d56a4-9a4d-4f68-a21a-bcdb109760df)

It seems there is very little activity on this project.

Are there maintainers? And if so do they have enough time & priority to merge PRs?

--> I'm not demanding anything from OS maintainers, but some communications so we can set our expectations would be great.

I could work on updating this library, I'm primarily interested in the core, think of things like:

- Move to more modern PHP (strict typing)
- Updating dependencies to latest major versions
- Fixing test pipelines on GH Actions
- Simplifying test runners where possible

**Comment by Blackbam** [comment]
@SamMousa Currently I am the maintainer as it looks. I am very experienced with PHP but my time budget is very limited at the moment. Do you want to set up a call to talk about that for 15 to 20 minutes? Please contact david.stoeckl@stack.holdings , would be glad if someone can help out with that!

**Comment by netvillage** [comment]
That's nice of you to offer your time to dude. (thumbs up)
