### ISSUE TITLE
Short / Alternate chain in acme-php ?

### ISSUE THREAD

**Issue by guldil** [acmephp/acmephp#273]
Hello,

I'm looking in the code where the chain is save because i'll have to continue to use "long chain" after February 2024.

https://community.letsencrypt.org/t/shortening-the-lets-encrypt-chain-of-trust/201580

Does anyone know where this is in the code?

I use an acme-php fork to get DNS validation from OVH.

Thanks

Guldil

**Comment by SamMousa** [comment]
> I'm looking in the code where the chain is save because i'll have to continue to use "long chain" after February 2024.

Since June 2024 has passed LE no longer supplies the long chain. 

>We have [just published a blog post 638](https://letsencrypt.org/2023/07/10/cross-sign-expiration.html) detailing our plans to handle the expiration of our ISRG Root X1 cross-sign from IdenTrust’s DST Root CA X3.

> The summary is:

> On 2024-02-08, we will stop providing the long chain by default, but clients can still be configured to request it.
> On 2024-06-06, we will stop providing the long chain at all.
> On 2024-09-30, the cross-sign will expire, and any websites still serving it in their TLS handshakes may run into difficulties.
> No action on your part is needed. You have the option of doing some manual configuration of your ACME client to gain six extra months of compatibility for older Android devices visiting your sites. If you have any questions, please direct them to [this thread 357](https://community.letsencrypt.org/t/questions-regarding-shortening-the-lets-encrypt-chain-of-trust/201581).

I'm closing this issue.

PS. Why not make a PR  for the OVH Resolver? That way we can offer it to other users as well.
