### ISSUE TITLE
Error in the docs

### ISSUE THREAD

**Issue by timmyrs** [acmephp/acmephp#28]
At https://acmephp.github.io/documentation/cli/get-certificate.html it says "This command will do four main things" even tho listed are only 3 things.
![image](https://cloud.githubusercontent.com/assets/11009697/18919727/82ca89a8-859f-11e6-97ab-71552a0f9020.png)

**Comment by tgalopin** [comment]
Thanks, I'll fix it :) .

**Comment by tgalopin** [comment]
Fixed: https://acmephp.github.io/documentation/cli/get-certificate.html
