### ISSUE TITLE
Upgrade PHP to V8

### ISSUE THREAD

**Issue by songxuan95** [acmephp/acmephp#285]
php 版本可以升级到 8.0版本吗？下面的可以升级吗？
guzzlehttp/guzzle: ^7.8
guzzlehttp/psr7: ^1.0

**Comment by Blackbam** [comment]
That question is about upgrade to PHP 8.

**Comment by Blackbam** [comment]
@SamMousa Maybe you can check if we can proceed here? Only if you find some time currently, of course.

**Comment by songxuan95** [comment]
![image](https://github.com/acmephp/acmephp/assets/49665721/b6033258-2530-4247-b747-d56584938643)
![image](https://github.com/acmephp/acmephp/assets/49665721/876d2efb-db72-4303-81af-f4ca15b7fbaa)
Thank you ！

**Comment by SamMousa** [comment]
> @SamMousa Maybe you can check if we can proceed here? Only if you find some time currently, of course.

https://github.com/acmephp/acmephp/issues/278
