### ISSUE TITLE
Staging on LE fails with key-change request

### ISSUE THREAD

**Issue by ivanjaros** [acmephp/acmephp#34]
Hi,
I am implementing the core into my app so that I can use LE and all is fine but one thing: if I use the staging directory it will always result in invalid argument exception stating: `Resource type ""key-change"" is not supported by the ACME server (supported: "new-reg", "recover-reg", "new-authz", "new-cert", "revoke-cert", "reg", "authz", "challenge", "cert")`. Funny thing is, the 'key-change' is not mentioned once in the code so I cannot figure out where this is coming from. If I switch to production no issues whatsoever.

I don't need to use staging that much but I'm just interested to know the reason for this.

**Comment by tgalopin** [comment]
Hello @ivanjaros!

I checked the code and there was indeed an issue in the resources validation in the ResourcesDirectory constructor.

I created https://github.com/acmephp/acmephp/pull/35 to fix it (the 1.0 stable release should follow soon, including it).

**Comment by tgalopin** [comment]
Don't hesitate to comment here if the issue is still present.

**Comment by tgalopin** [comment]
The beta3 release should fix the issue, please tell me if you still have the problem.

**Comment by ivanjaros** [comment]
Seems like the change hasn't been merged into acmephp/core since there is only beta 2 available.

**Comment by tgalopin** [comment]
Indeed, I forgot to sync the splitted repository. I should really automate this.

I did it, you should now be able to get it.

**Comment by ivanjaros** [comment]
Works like a charm. Thanks!
