### ISSUE TITLE
Key challenges by type

### ISSUE THREAD

**Issue by ivanjaros** [acmephp/acmephp#36]
Hi,
the method \AcmePhp\Core\AcmeClient::requestAuthorization transforms the response into an array of AuthorizationChallenge objects. There are only tree types of challenges now and if I want to get the information for the sepcific challenge I want to use I have to filter this array. I think that is an unnecessary step and the challenges should be keyed by the type of challenge they represent.

So instead of this:
```
$authorizationChallenges = [];
        foreach ($response['challenges'] as $challenge) {
            $authorizationChallenges[] = new AuthorizationChallenge(
                $domain,
                $challenge['type'],
                $challenge['uri'],
                $challenge['token'],
                $challenge['token'].'.'.$encodedHeader
            );
        }

        return $authorizationChallenges;
```

it should be like this:
```
$authorizationChallenges = [];
        foreach ($response['challenges'] as $challenge) {
            $authorizationChallenges[$challenge['type']] = new AuthorizationChallenge(
                $domain,
                $challenge['type'],
                $challenge['uri'],
                $challenge['token'],
                $challenge['token'].'.'.$encodedHeader
            );
        }

        return $authorizationChallenges;
```

**Comment by tgalopin** [comment]
Hello @ivanjaros!

Thanks for your suggestion, I'm really busy nowadays but I'll review it this week-end.

**Comment by tgalopin** [comment]
I thought about this and I checked the specification: the type is can be non-unique. Technically, any Acme server could support multiple times a type (`http-01` for instance) with multiple different URLs. I want the AcmePHP client to stick strictly to the specification so I prefer not to change this. I think the external check is not that much of a problem and can even be useful in some cases.

Thanks for your proposal :) !
