### ISSUE TITLE
What to put into the challenge?

### ISSUE THREAD

**Issue by ivanjaros** [acmephp/acmephp#37]
Hi,
I am trying to generate a certificate(currently by DNS challenge) and I can get challenge(s) but so far I have tried to provide the token, the payload, the second part of the payload(which is the hashed header) and in all cases the validation has failed.

I have checked the docs in here https://letsencrypt.github.io/acme-spec/#rfc.section.7.4 and it sounds to me like after I get the challenge I have to request the token which will be the returned value or something like that.

What is the value that has to be returned and where do I get it? The LE is effing frustrating to work with.

PS: I have AcmePHP core only.
PS2: http challenge works right away.

**Comment by tgalopin** [comment]
Hello @ivanjaros !

I'm sorry for not answering this issue faster but I'm working on improving the Core documentation and it should be useful for your use-case.

For the moment, I have to admit that I'm not sure what would be the best practice on how to create and use the client with DNS challenges (it's the same idea as HTTP, but the checking is different, so it would probably require a bit of logic on your side). I'm working on it, I'll get back at you when I properly studied it :) .

Thanks for your feedback!

**Comment by ivanjaros** [comment]
Hi, the issue is not with setting the DNS(that is user's problem) but with the "secret" not being accepted by LE.
Anyway, I have moved to HTTP challenge since.

**Comment by tgalopin** [comment]
Hello,

I'll write the documentation about the Core then. I close this issue if you fixed your problem :) .
