### ISSUE TITLE
Problem renewing certifcates

### ISSUE THREAD

**Issue by msebel** [acmephp/acmephp#38]
When authorizing (or doing any command) with a domain where we already created a certificate, the following message is printed to the command line on every command, for example:

Command: php acmephp.phar authorize -s http brucht.me

Output:
~~
Loading account key pair...
Requesting an authorization token for domain brucht.me ...

  [InvalidArgumentException]
  Resource type ""key-change"" is not supported by the ACME server (supported: "new-reg", "recover-reg", "new-authz", "new-cert", "revoke-cert", "reg", "authz", "challenge", "cert")

authorize [-s|--solver SOLVER] [--] <domain>
~~

I already tried to debug the current release, but I can't seem to find out where a request with the resource type key-change is actually fired and why it's fired.

I have exactly 10 days left before around 100 client certificates are going to expire, so any help with debugging this would be greatly appreciated.

**Comment by msebel** [comment]
Actually, the same InvalidArgumentException also appears when we just type:
php acmephp.phar authorize help

Is the installation kind of... broken? Creating new certificates works fine though.

**Comment by tgalopin** [comment]
Hello @msebel !

This was an update of Let's Encrypt, adding a resource type we did not handle with this client. The fix was merged in master a few days ago and I will release it either this night or tomorrow. I'll keep this issue open so you will be able to easily tell me if the new version does not fix your probem.

**Comment by msebel** [comment]
@tgalopin You da real MVP!
And yes, I got the help command mixed up badly :-).

I'il keep you updated as soon as we tested the new version.

**Comment by tgalopin** [comment]
I just released the beta3 which should solve the issue. Please tell me if it's not the case.

Also, I just noticed in your first message that you wanted to renew certificates: you don't need to re-run `authorize` for renewal. Once you are the proved owner of a domain, the private key generated by Acme PHP is enough to renew the certificate by running the same `request` command again.

**Comment by msebel** [comment]
Works as expected, I was able to renew all certificates. Thanks for the fast update!

Our script is still very prototypey, hence we still to a new authorization everytime, but with acmephp we we're able to provide about 100 customers with fully automated ssl, deploying the certificates to 3 loadbalancers. I definitely need to refactor our automation :-)

**Comment by tgalopin** [comment]
I'm glad it's working properly. Your context and usage is interesting indeed :) ?
