### ISSUE TITLE
Unused `RECOVER_REGISTRATION` Resource

### ISSUE THREAD

**Issue by cpu** [acmephp/acmephp#39]
Hi there,

I noticed [ResourceDirectory.php](https://github.com/acmephp/core/blob/fbd4dadae158f1fd475ae996ca9a96eb79a99c7b/Protocol/ResourcesDirectory.php) includes a `RECOVER_REGISTRATION` resource for `/recover-reg`.

You should be able to delete this outright. It doesn't look like this constant is used anywhere outside of the directory. It also isn't present in the latest ACME draft specifications and isn't implemented by Boulder/Let's Encrypt.

Thanks!

**Comment by tgalopin** [comment]
Hello @cpu !

I'm glad a Let's Encrypt core member as you take a look around here :) . I'll change this, thanks for the tip!
