### ISSUE TITLE
dns-01 Challenge

### ISSUE THREAD

**Issue by kevinquinnyo** [acmephp/acmephp#4]
Hi @tgalopin,

You mentioned in #3 that if I had any other questions, feel free to ask, so I'm cashing in on that offer.  ;)

So I have just a few.

1.  With the dns-01 challenge (yet to be implemented here, but I know it's on the todo list), it should automatically cover any subdomains in the certificate's Subject Alternate Name right?  For instance if the certificate were for `mydomain.com` and the SAN had `www.mydomain.com` a single, successful dns-01 challenge that had the appropriate TXT record would be sufficient to cover both, and we could then get a certificate?

 - Right now we are having to issue two http-01 challenges, one for `mydomain.com`, and another for `www.mydomain.com`, (even though they point to the same IP in 99% of cases) so we're trying to streamline that process if possible.  And my thought was that implementing the dns-01 challenge *might* solve that.  I'm not sure.

2.  If I'm correct about that, are you already working on implementing the dns-01 challenge?  We were thinking about forking the code and submitting a PR, but I'm sure you would be able to do it faster than us and probably already have an idea on how you want to design the code to handle this, especially if you're already working on it.

Thanks again for the awesome library

**Comment by tgalopin** [comment]
Hello @kevinquinnyo,

Challenge are not linked to what certificate type you can issue. If you proved you are the owner of a given domain by successfully completing a challenge of any kind, the result will always be the same: you will be able to request single-domain and multi-domain certificates for the domain.

With the ACME protocol, you will be able to request certificates for a fixed amount of domains (no wildcard certificate). As you said, using the `Subject Alternate Name` for a given certificate, you will be able to acheive what you want: get a single certificate working for both a www and non-www domain.

I suggest you to use `mydomain.com` as the main domain and `www.mydomain.com` as a Subject Alternate Name. The code could be something like:

``` php
<?php

$keyPairGenerator = new KeyPairGenerator();

$domainKeyPair = $keyPairGenerator->generateKeyPair();

$csr = new CertificateRequest(
	new DistinguishedName('mydomain.com', 'FR', 'France', 'Paris', 'AcmePHP', null, 'myemail@example.com', [ 'www.mydomain.com' ]),
	$domainKeyPair
);

$client = new AcmeClient();
$client->requestCertificate('mydomain.com', $csr);
```

(Note that I didn't test this code, it's just an idea of how it could work :) ).

For the dns-01 implementation, I tried to work on it a bit but creating functionnal tests for it is quite difficult :) . I'll see how I can dot this properly. For the moment, the most convenient and usable challenge type is http-01 :) .

**Comment by kevinquinnyo** [comment]
The issue I was running into yesterday was that when trying to get the certificate, letsencrypt would respond that www.mydomain.com is not authorized, which would throw an AcmeHttpErrorException:

```
The ACME server returned the error HTTP status code during request to https://acme-staging.api.letsencrypt.org/acme/new-cert (detail: 403 Error creating new cert :: Authorizations for these names not found or expired: www.mydomain.com)
```

So I think to solve it I have to fulfill two http-01 challenges?  One for mydomain.com and another for www.mydomain.com?

**Comment by tgalopin** [comment]
Indeed, you have to be the proved owner of the two domains. However, once you have proved that (using the http-01 challenge yes :) ), you can request a single certificate valid for both domains, using the method I gave you in the precedent post.

**Comment by kevinquinnyo** [comment]
@tgalopin Thanks.  Yeah the only reason I'm very interested in the dns-01 challenge is because I assume it will be a single check that will cover any subdomains in the SAN, or an alias or redirect subdomain with one singular challenge.

The reason that's important to me moving forward is because I'm using your library to build out a PAAS of sorts and the easier I can make it for the end-user, the better.  If they haven't switched dns over to us yet, and all they have to do is add a single TXT record, that would be ideal.

But we can make the http-01 work for now, and I understand that mocking/testing for the dns challenges is not trivial.

**Comment by tgalopin** [comment]
I see your idea, that would be indeed ideal. For the moment, I have a lot of work besides this project, so I won't be able to implement the DNS challenge properly for now. However, if you want to start to work on it in a PR to implement it in your project, I would be happy to give a hand :) . The implementation itself is not that complicated I think (it's simply a matter of understanding what to put in the TXT field), what's difficult is the testing behind.

**Comment by kevinquinnyo** [comment]
@tgalopin I understand completely.  I might give it a shot and submit a PR soon.

**Comment by tgalopin** [comment]
I planned this for 1.1 for the moment (other people asked for it too), but if I have time and find how to do it properly I would like to put it in 1.0 stable.

**Comment by kevinquinnyo** [comment]
:+1:

**Comment by tgalopin** [comment]
The PR https://github.com/acmephp/acmephp/pull/25 is almost ready, I think this will be ready for 1.0 stable (probably beta2).

**Comment by tgalopin** [comment]
Released in beta2 :)
