### ISSUE TITLE
bin/acme should check one directory higher for autoload.php

### ISSUE THREAD

**Issue by mikemunger** [acmephp/acmephp#42]
Hi there,

Rather than using the phar, I am running the bin/acme file - but as-is it fails unless I tell it to look one directory higher for the composer autoload file like this:

```
$autoload = [
    __DIR__.'/../../../autoload.php',
```

because after a composer install, the folder structure will be: vendor/acmephp/acmephp/bin , making bin need to look 3 folders up to be in vendor to then find autoload.php.

Unless maybe I am doing something wrong?

Great work so far, thank you.

**Comment by tgalopin** [comment]
Hello @mikemunger!

You are completely right, I fixed this in https://github.com/acmephp/acmephp/pull/44.

Thanks for your feedback!
