### ISSUE TITLE
Adding subdomain to existing certificate

### ISSUE THREAD

**Issue by gmgarrison** [acmephp/acmephp#46]
I've got the certificate for an unqualified domain setup then later tried to add a subdomain. I received this error:

Requesting first certificate for domain ********* ...  
                                                                                                                           
  [AcmePhp\Core\Exception\Server\UnauthorizedServerException]                                                              
  [unauthorized] The client lacks sufficient authorization: Error creating new cert :: Authorizations for these names not found or expired: ********* (on request "POST https://acme-v01.api.letsencrypt.org/acme/new-cert")         
                                                                                                                          
  [GuzzleHttp\Exception\ClientException]                                                                           
  Client error: `POST https://acme-v01.api.letsencrypt.org/acme/new-cert` resulted in a `403 Forbidden` response:  
  {                                                                                                                
    "type": "urn:acme:error:unauthorized",                                                                         
    "detail": "Error creating new cert :: Authorizations for these names not fo (truncated...)

Any tips on how to debug this? Thank you!!

**Comment by tgalopin** [comment]
Hello! 

This indicates you are not the proved owner of the subdomain. Let's encrypt forces you to prove your ownership over each domain and subdomain you want to request. 

Simply run the authorization process with the subdomain.
