### ISSUE TITLE
Ability to specify alternate services.xml file for Cli client

### ISSUE THREAD

**Issue by mikemunger** [acmephp/acmephp#48]
Hello,

Is there a way to specify overriding the services.xml file for the Cli client?

Here is my thought process: I like 98% of what the Cli client does such as handling storage and making calls to the LE api, and I was hoping to override the last 2% with some custom service classes rather than building 100% of a custom Cli client alternative myself. I'm hoping to just modify a few small behaviors, but without touching the distribution files so I can continue to update with composer.

It seems like being able to specify a custom services.xml file would open up a lot of capabilities like this, but please let me know if there is a way to achieve a similar result already and I might just be thinking about this wrong?

Thank you

**Comment by tgalopin** [comment]
Hello @mikemunger,

We do have a problem of decoupling things in the CLI (we saw it a few weeks ago, but we wanted to focus on releasing a stable for now). I don't think we should provide the possibility to override the default `services.xml`, I would prefer instead to create a `acmephp/storage` or `acmephp/common` repository to provides features such as making calls and storing results in a directory.

If you want to work on this, I would be happy to give you a hand to start decoupling stuff :) . Feel free to join us on Gitter (https://gitter.im/acmephp/acmephp) :) .

Thanks for your feedback!
