### ISSUE TITLE
CertificateParser fails with CloudFlare certificates

### ISSUE THREAD

**Issue by ivanjaros** [acmephp/acmephp#50]
Hi,
I have site secured by the CloudFlare DNS and it provides its own ssl certificate that handles communication from client to DNS/CloudFlare. But communication from CF to server is not encrypted so CF offers free SSL certificate(or you can upload your own) for this purpose. I have opted for the free one(since it can be valid for 15 years it you like = no hassle with updating LE). I am trying to put it into my system that handles proxying and other stuff and the CertificateParser class will fail to parse the certificate because of missing issuer[CN] value.

So I am wondering who got this wrong - the parser or the issuer?

**Comment by tgalopin** [comment]
Hello @ivanjaros,

That's probably a bug on our side (we designed the SSL library with the Let's Encrypt certificates in mind). Can you paste your certificate here so I can fix the bug?

Thanks by advance!

**Comment by ivanjaros** [comment]
```
-----BEGIN CERTIFICATE-----
MIIEkjCCA3qgAwIBAgIUYOsBJUCnVkjrZKLXhz6uGeE+bfAwDQYJKoZIhvcNAQEL
BQAwgYsxCzAJBgNVBAYTAlVTMRkwFwYDVQQKExBDbG91ZEZsYXJlLCBJbmMuMTQw
MgYDVQQLEytDbG91ZEZsYXJlIE9yaWdpbiBTU0wgQ2VydGlmaWNhdGUgQXV0aG9y
aXR5MRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMRMwEQYDVQQIEwpDYWxpZm9ybmlh
MB4XDTE2MTIxNjA2NDMwMFoXDTMxMTIxMzA2NDMwMFowYjEZMBcGA1UEChMQQ2xv
dWRGbGFyZSwgSW5jLjEdMBsGA1UECxMUQ2xvdWRGbGFyZSBPcmlnaW4gQ0ExJjAk
BgNVBAMTHUNsb3VkRmxhcmUgT3JpZ2luIENlcnRpZmljYXRlMIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6PiWC1ic15fnGgSPbWKgLWyUHw2AAPDQAmNb
sr+8zYfP5GBeA7p+F0W4n6cy09E4Ofo4X5enaGcPY5xpn17HRrneu0T54jaGKVBK
17Ip088uee28WVMzirtVMn3AUHwj6LGtLnpYXWpMIXvFE7A0qGMPuoQpgiNh3Ty4
blR48vbHkbyKP1kWmL8xormueXbxPoppdmM0EhuCHCzcl3YGapTYBxq5IigEUSeM
svGTIV7xTkHp1Y1lvG913d8MLQhuBrAr+IDmwbfJsZlKrdS/QReizfaOY+aagC5L
/Ewmin1r3Z5oBtweCEprDhUZQxAjO7ixp2hRDLQxa0TtYuAnyQIDAQABo4IBFDCC
ARAwDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB
/wQCMAAwHQYDVR0OBBYEFBtvpeo/GwVK4al5C+nC8n72lDaFMB8GA1UdIwQYMBaA
FCToU1ddfDRAh6nrlNu64RZ4/CmkMEAGCCsGAQUFBwEBBDQwMjAwBggrBgEFBQcw
AYYkaHR0cDovL29jc3AuY2xvdWRmbGFyZS5jb20vb3JpZ2luX2NhMB8GA1UdEQQY
MBaCCioubXFjZG4uY3qCCG1xY2RuLmN6MDgGA1UdHwQxMC8wLaAroCmGJ2h0dHA6
Ly9jcmwuY2xvdWRmbGFyZS5jb20vb3JpZ2luX2NhLmNybDANBgkqhkiG9w0BAQsF
AAOCAQEAQzFUegjhjwPuc4Hm5sT6u2qjujPRS+b9cMMht2SF29P/h4QMe/6hfKwk
vmRCTa5sqpzKC+paFtEPiUYcqrsn/zUKhBWpx9tWQpPFicnZLNCFcAkMuGA8xsDe
zcSWDGK5n8GCdofWVrN3dXJ9Bs6gMSqZEkfjkWaLe6PonEwjR4gT8feMBH9+QlKt
sVukLJ0Y8NynHAejoTvs2jpZbmzU5ywXCV1CQVBfbqDppZq8kqWakazxWEmYk2TY
QhYb566EvoLnFHbYvEMAM92tx9CAlPcrVA1fqbxKOJGguNdMw826e1iI7mNp2l0z
IVpfS/F2WV6y/Oh2mPNGqplqZpGjng==
-----END CERTIFICATE-----
```

**Comment by tgalopin** [comment]
Thanks! I see you don't have included the whole chain, did you simply put the `cert.pem` file in Cloudflare? Maybe it's the problem: you need to specify the complete chain (`fullchain.pem`) so Cloudflare can trust your certificate.

**Comment by ivanjaros** [comment]
No, it's not like that. That is cert issued by them to me. Their service works in a way that they provide their own SSL cert for your domain that you point to their DNS which makes the communication secure from client/visitor to the CF DNS/NS server but from there to you(your physical server) it is insecure.  For this reason they offer free unlimited SSL certificate that you can use on your server(equivalent of LE cert but without that small lifespan). This cert will be encrypting communication from the DNS server to your server so the whole connection client -> DNS -> server is secure. I have put that cert into work and no issues beside it failing with that Acme class parser.

**Comment by tgalopin** [comment]
Oh ok, I got it. I'll work on this then, thanks!

**Comment by ivanjaros** [comment]
It's all about this: https://github.com/acmephp/acmephp/blob/master/src/Ssl/Parser/CertificateParser.php#L45

so that's why I was asking if this is "bug" on Acme PHP's part of CloudFlare's.

**Comment by tgalopin** [comment]
It's fixed in master and it will be released in the next release :) .
