### ISSUE TITLE
self-update var_dump() with 1.0.0-dev?

### ISSUE THREAD

**Issue by flo-sch** [acmephp/acmephp#57]
Hey,

Not sure if it's actually a bug, but in the {IMO} last-version, the self-update end-up in a var_dump of the available versions, without actually any way to finish the update (choose a version manually?).

Am I missing something?

It is not a main issue, acmephp works fine otherwise, but I was curious :)

```
$ php acmephp.phar -V

Acme PHP - Let's Encrypt client 1.0.0-dev
```

```
$ php acmephp.phar self-update
Updating...

array(9) {
  [0]=>
  string(10) "dev-master"
  [1]=>
  string(18) "dev-custom-actions"
  [2]=>
  string(14) "dev-improve-dx"
  [3]=>
  string(11) "1.0.0-beta3"
  [4]=>
  string(11) "1.0.0-beta2"
  [5]=>
  string(11) "1.0.0-beta1"
  [6]=>
  string(13) "1.0.0-alpha10"
  [7]=>
  string(12) "1.0.0-alpha9"
  [8]=>
  string(12) "1.0.0-alpha8"
}
```

**Comment by tgalopin** [comment]
Oops, that's indeed not normal :D. I'll fix it as soon as I get a computer :)

**Comment by flo-sch** [comment]
Not urgent ;)

I just do not find by myself which branch is concerned, or where it could come from...

**Comment by tgalopin** [comment]
The development version is manually deployed, it simply comes from an old broken artifcate I uploaded. Sorry for the mistake :) . I fixed it, you can redownload the dev PHAR.

**Comment by flo-sch** [comment]
( Sorry forgot to answer, but indeed it works perfectly now, thanks for your reactivity! :) )
