### ISSUE TITLE
change storage location or copy to another location

### ISSUE THREAD

**Issue by redemption** [acmephp/acmephp#62]
Hi there,

Wonderful tool, thanks for making it.

I'm wondering whether there's a way to change the path where files are stored, or else how to configure the post_generate in order to move or copy the generated files or directory to another location.

Eg right now the location is:

/root/.acmephp/master/certs/domain.org/cert.pem

And I want to have a copy at:

/foo/bar/ssl/domain.org/cert.pem

For various reasons I can't just rely on a symlink, I need the file to be in that location.

**Comment by tgalopin** [comment]
Hello @redemption!

For the moment it's not possible easily, but it can be added as a post-generate action indeed. I don't have much time lately to work on such a feature, but if you can wait (or even work on it :) !), it's a great idea I would like to add toe AcmePHP.

Thanks for your feedback!

**Comment by Darunada** [comment]
+1 this would help me out a lot

**Comment by stefanpolzer** [comment]
+1 Wonderful tool but without this, I can't us it

**Comment by Darunada** [comment]
@stefanpolzer I ended up cloning the repos, changing the paths, and building the phar myself.  I messed with putting it into the config but like @tgalopin said it isn't easy.  Good luck!

**Comment by tgalopin** [comment]
I'll have a look as soon as possible on this.

**Comment by jderusse** [comment]
once #100 merged, it would be possible to mirror files to a an other location.

```
- action: mirror_file
  adapter: local
  root: /where/you/want
```

Note that you can also use ftp/sftp
