### ISSUE TITLE
LibreSSL support?

### ISSUE THREAD

**Issue by flo-sch** [acmephp/acmephp#63]
Not actually sure if this is possible, but it might be interesting for acmephp to be libressl-compatible?

This library is a modern rework of openssl, security-wise best-practice based, reducing the risk of vulnerabilities...

Just suggesting :)

> http://www.libressl.org/

**Comment by tgalopin** [comment]
Technically, if LibreSSL is a fork of OpenSSL and works with the PHP OpenSSL extension it should work without specific code on AcmePHP side. Can you try?

**Comment by flo-sch** [comment]
Yep, I figured this out right after asking actually... I'll set-up a VM to test it next week!
