### ISSUE TITLE
Unable to renew certificate?

### ISSUE THREAD

**Issue by MarcusHKrueger** [acmephp/acmephp#64]
I am unable to renew the certificates on my 2 domains. One has already expired, the other is about to. I updated to the beta-2 and reran the commands with no luck. The cert files and such are also not being updated. Any idea what I could be doing wrong here?

http://i.imgur.com/jWAagJl.png

**Comment by tgalopin** [comment]
Can you try with the latest Beta?

**Comment by Waizujin** [comment]
With the latest version, dev, I get

http://i.imgur.com/VPI1ER8.png

So somehow my domain is now not authorized? I have to go through the entire process again? Or am I misreading things? I just hope this doesn't happen everytime.

**Comment by tgalopin** [comment]
Hello @Waizujin,

I think you stumbled a problem we had in beta2 that I was not able to track down. Can you remove the beta2 (or dev) phar, redownload the beta4 one (https://github.com/acmephp/acmephp/releases) and redo the process of request from the beginning? It seems indeed you need to reauthorize your server. You shouldn't have to do it in the future though.

Sorry for the inconveniance.

**Comment by chokyice92** [comment]
Hi there,

I've got the same issue (certificate expired)
`php acmephp.phar request  www.example.org`
```
Loading account key pair...
Current certificate will expire in less than a week (2017-03-02 22:00:00), renewal is required.
Loading domain key pair...
Loading domain distinguished name...
Renewing certificate for domain www.example.org ...


  [AcmePhp\Core\Exception\Server\UnauthorizedServerException]
  [unauthorized] The client lacks sufficient authorization: Error creating new cert :: Authorizations for these names not found or expired: www.example.org (on request "POST https://acme-v01.api.letsencrypt.org/acme/new-cert")



  [GuzzleHttp\Exception\ClientException]
  Client error: `POST https://acme-v01.api.letsencrypt.org/acme/new-cert` resulted in a `403 Forbidden` response:
  {
    "type": "urn:acme:error:unauthorized",
    "detail": "Error creating new cert :: Authorizations for these names not fo (truncated...)


```
Weird because 2017-03-02 is not ine less than a week, it's in the past).

So I tried to authorize again, then when I:
`php acmephp.phar check -s http  www.example.org`
I've got this:
```
Loading account key pair...
Loading the authorization token for domain www.example.org ...
Testing the challenge...


  [GuzzleHttp\Exception\RequestException]
  cURL error 60: SSL certificate problem: certificate has expired (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

```

Tested with 1.0.0-dev and 1.0.0-beta4.
Can you please have a look at this? I've got 3 production sites down and don't figure out how to restore the certs...
Thanks,

**Comment by Waizujin** [comment]
I wasn't able to fix the issue, even after redoing everything. So I just switched to CertBot and moved on.

**Comment by gacekssj4** [comment]
I have exactly same problem. Do I need to authorize every domain over and over everytime I want to renew certificate? All automation magic goes away and becomes hard labour....

**Comment by gacekssj4** [comment]
@chokyice92 Check, if you dont have any kind of force redirect to SSL. If certificate expired it probably can't open url with validation. Had same issue and had to disable all SSL on all sites.

**Comment by pdbreen** [comment]
Any update on this?  I had to re-authorize every server before it would accept the renewal requests.  As @gacekssj4 mentioned, this kind of kills the promised automation!

In case its helpful, when I ran a check prior to re-authorizing, this is what came back:

```
  [AcmePhp\Core\Exception\Server\MalformedServerException]
  [malformed] The request message was malformed: Expired authorization (on request "POST https://acme-v01.api.letsencrypt.org/acme/challenge/ixlQuwZRDyOW0uHWrMqUfoc8awHiDEruhJqb
  F3NaaKU/622077675")



  [GuzzleHttp\Exception\ClientException]
  Client error: `POST https://acme-v01.api.letsencrypt.org/acme/challenge/ixlQuwZRDyOW0uHWrMqUfoc8awHiDEruhJqbF3NaaKU/622077675` resulted in a `404 Not Found` response:
  {
    "type": "urn:acme:error:malformed",
    "detail": "Expired authorization",
    "status": 404
  }
```

I know nothing of the protocol, but this seems to suggest authorization needs to be refreshed periodically as well?

**Comment by tgalopin** [comment]
Indeed, this seems to indicate so. I'm not sure why, perhaps did the protocol change recently and I missed it. I have to admit I don't have much time right now (busy for work), but as soon as  I can I will have a look. In the meantime, don't hesitate to rerun the authorization process.

I'm sorry for the incovnenience, that's the issue with having to deal with an unstable protocol :/ .

**Comment by redemption** [comment]
Hi there, is there any sort of update on this?  I just encountered the exact same problem.

**Comment by babblo** [comment]
Hi, same problem here. Just wanted say that I was able to renew a cert.. these were the steps.

- Tried to renew, got the error.
- Deleted everything about the domain inside .acmephp folder.
- Started a new authorization, etc.
- Got the new cert.
- Just to see what could happen, tried to renew.. and voila. cert was renewed without problem.

Hope this help @tgalopin to figure out whats happening.

**Comment by tgalopin** [comment]
@babblo thanks for the information.

It seems your private key was corrupted somehow, ro didn't match the authorization stored on the Let's Encryt server. I'm not sure why this is happening :/ .

**Comment by humayunghani** [comment]
@tgalopin Same problem here AcmePHP using v1.0.0-dev. But i'm more afraid of whether this renewal issue might happen with the core client library as well? I implemented acmephp using core/AcmeClient.php. I have quite a lot certs starting going to expire from 9th July.

**Comment by tgalopin** [comment]
@humayunghani in the worst case scenario, you might ahve to redo the authorization process as well (which you probably integrated in your code). But indeed, the default renewal may not work, and I have no idea why because it's working now. Perhaps were there a purge in the Let's Encrypt servers that made your authorizations expires earlier than expected :/ .

**Comment by tgalopin** [comment]
To all who have this issue, please note that rerunning the authorization process work properly and will let you renew your certificates.

**Comment by humayunghani** [comment]
Ok thanks a lot. I'll re-run authorization for all domains.

**Comment by tgalopin** [comment]
@TheJoin95 probably found the issue here: https://github.com/acmephp/acmephp/issues/71 I will update the code to fix this.
