### ISSUE TITLE
Registering key error

### ISSUE THREAD

**Issue by JonasBVS** [acmephp/acmephp#65]
getting this while trying to do initial register

[InvalidArgumentException]
  Resource type ""key-change"" is not supported by the ACME server (supported
  : "new-reg", "recover-reg", "new-authz", "new-cert", "revoke-cert", "reg",
  "authz", "challenge", "cert")

**Comment by tgalopin** [comment]
Hello!

What version are you using? Can you update to the latest if you are not using it and retry?

**Comment by JonasBVS** [comment]
just following this to the letter :)
https://acmephp.github.io/documentation/getting-started/1-installation.html

**Comment by tgalopin** [comment]
Oh indeed, I forgot to update this page. You can replace beta2 by beta4 :) .

**Comment by samlittler** [comment]
@tgalopin Thanks, problem solved.
