### ISSUE TITLE
Renew certification Issue

### ISSUE THREAD

**Issue by Sh1nto** [acmephp/acmephp#70]
Hi, i'm Using beta4 and have the Same Issue for the second time:
 ```
[AcmePhp\Core\Exception\Server\UnauthorizedServerException]
  [unauthorized] The client lacks sufficient authorization: Error creating new cert :: authorizations 
for these names not found  or expired: mydomain.de, www.mydomain.de 
(on request "POST https://acme-v01.api.letsencrypt.org/acme/new-cert")
```
 ```
 [GuzzleHttp\Exception\ClientException]
  Client error: `POST https://acme-v01.api.letsencrypt.org/acme/new-cert` resulted in a `403 Forbidden` response:
  {
    "type": "urn:acme:error:unauthorized",
    "detail": "Error creating new cert :: authorizations for these names not fo (truncated...)
```

The domains will expire in 1week. I'm using the following Syntax in the daily cron:

```
php /root/acmephp.phar request mydomain.de -a www.mydomain.de -q
```

I'm Missing something? It doesn't make fun to authorize > 20domains every 3month,...

**Comment by dfritschy** [comment]
Unfortunately, I have to confirm your findings. Obviously we have the same issue as in #52, and going through authorization every 3 months is really annoying. @tgalopin have you lost interest in your project?

**Comment by tgalopin** [comment]
I'm sorry about this issue, I investigated it a few times and did not find any reason why it's happening. I have not lost interest in the project but open-source does not pay the bills unfortunately :) . I will give a look asap, sorry for the inconvenience.

**Comment by tgalopin** [comment]
@TheJoin95 probably found the issue here: https://github.com/acmephp/acmephp/issues/71 I will update the code to fix this.

**Comment by jderusse** [comment]
can you try the new "run" command?

**Comment by tgalopin** [comment]
I just deployed a new version of the documentation, including explanations on how to use the `run` command: https://acmephp.github.io/documentation/getting-started/2-obtain-certificate-easy.html.

This should help here :) . Don't hesitate to ping me if needed!
