### ISSUE TITLE
Is There An Alternative To --expand

### ISSUE THREAD

**Issue by PK232** [acmephp/acmephp#74]

**Comment by PK232** [comment]
Sorry - didn't mean to post without a description.

I wanted to add the www sub-domain to my certificate that I generated with acmephp and I thought the syntax would be

php acmephp request mydomain.com -a www.mydomain.com --expand 

It looks like the --expand switch is not available using acmephp.   What would be the best way of adding a sub-domain to an existing certificate?

**Comment by tgalopin** [comment]
Hello @PK232 !

For the moment this is not possible, but it's a good idea. Thanks for the proposal :) .

**Comment by jderusse** [comment]
I suggest to use the new run command and update the .yml file to add new domains. The run command is optimized to request only new domains
