### ISSUE TITLE
Possibility to write authorization tokens to file

### ISSUE THREAD

**Issue by gacekssj4** [acmephp/acmephp#75]
It would be awesome idea, to allow us to store auth files that need to be created on FTP to file. Currently I haven't found command for it. So I can create all files, upload them via FTP and then run acmephp.phar check on domains.
Thanks in advance

**Comment by tgalopin** [comment]
Hello,

I'm not sure to understand what you mean. You would like to push your certificates and key pairs by FTP on a remote server?

**Comment by jderusse** [comment]
IMO the best way to do it is to implement a custom solver in charge of uploading the files at the right place. See Route53 solver for instance
