### ISSUE TITLE
Enhancement: Option for storage of conf and key pair

### ISSUE THREAD

**Issue by LeftPinkie** [acmephp/acmephp#76]
Can you add option to store / retrieve the conf and key pairs from a different location than the default `~/.acme/`?

**Comment by tgalopin** [comment]
Hello @LeftPinkie,

It is not possible to change the location of storage of Acme PHP (at least not for the moment) but I think the feature request https://github.com/acmephp/acmephp/issues/62 would solve your issue, wouldn't it?

**Comment by LeftPinkie** [comment]
Yes, that would solve it.  I'll close this issue and follow the feature reqest #62.
