### ISSUE TITLE
Monitoring send email via sendmail or php mail()

### ISSUE THREAD

**Issue by LeftPinkie** [acmephp/acmephp#77]
Enhancement request...

In addition to SMTP, allow th monitoring emails to be sent using sendmail or PHP's mail().

**Comment by axel-rutz** [comment]
YES, that would ease a lot. This should be quite easy to implement:

In EmailHandlerBuilder, check if smtp host is set. If not, use the NativeMailerHandler instead of the SwiftMailerHandler.

**Comment by LeftPinkie** [comment]
Actually I am requesting this be compiled into the .phar and implemented via the `~/.acmephp/acmephp.conf` config file.  Currenntly, it says only SMTP is supported for the monitoring email.

**Comment by tgalopin** [comment]
Hello @LeftPinkie,

Thanks for the proposal, it would be indeed useful. Would you have time to try to work on it? This would involves updating https://github.com/acmephp/acmephp/blob/master/src/Cli/Monitoring/EmailHandlerBuilder.php, it shouldn't be too difficult (get the config, check if the "transport" option is defined and what values it is and send the mail using the appropriate transport). Would you be interested in giving it a try :) ? I can help you do so if you want.

**Comment by LeftPinkie** [comment]
I will give it a try.

**Comment by tgalopin** [comment]
Awesome, thanks! Don't hesitate to ping me here or on Twitter (https://twitter.com/titouangalopin) if you need a hand :) .

**Comment by LeftPinkie** [comment]
I am re-thinking this request.  For the purpose of cross-platform compatibility, using sendmail or PHP mail() on a Windoze system may be problematic if PHP is not configured correctly.  Since I don't have access to a Windoze platform to test... is it really worth implementing this request just for Linux?  I am thinking SMTP is universal enough.  Any thoughts?

**Comment by tgalopin** [comment]
I think it's worth it, especially because you only have to rely on SwiftMailer SendMail transport: https://swiftmailer.symfony.com/docs/sending.html#the-sendmail-transport, the aim being only to choose between the SMTP or SendMail transport on https://github.com/acmephp/acmephp/blob/master/src/Cli/Monitoring/EmailHandlerBuilder.php#L49. It does not involves a lot of complexity :) .

**Comment by axel-rutz** [comment]
Another +1 for it's worth it. For a good coder it's faster to implement that than set up a SMTP server ;-).
Also some people (including me) don't like  having SMTP passwords on a config file. Once pushed to a public repo and we have another Spamgun.
