### ISSUE TITLE
Plugins for acmephp

### ISSUE THREAD

**Issue by grzchr15** [acmephp/acmephp#82]
To further automate the certificate creation process it woud be helpfull to have the DNS challenge supported with plugins for a range of DNS Providers ( to direct create the TXT DNS entries ).

php acmephp.phar authorize --solver dns yourdomain.org --dns-provider dns-plugin

php acmephp.phar setup --dns-provider dns-plugin to setup  creditentials, server endpoints ..

where dns-plugin could be any DNS server with an API
kasserver see http://kasapi.kasserver.com/dokumentation/phpdoc/packages/API%20Funktionen.html
ispconfig see https://www.howtoforge.com/how-to-create-remote-api-scripts-for-ispconfig-3

I am willing to create those plugins but we should agree how to add this plugin support to acmephp

**Comment by grzchr15** [comment]
https://certbot.eff.org/docs/contributing.html#dev-plugin
https://certbot.eff.org/docs/using.html#combining-plugins

How do you/we want to support dynamic discovery of plugins for Authenticator ( acme.challenge for DNS APIs) and Installers for certain webservers?

**Comment by tgalopin** [comment]
Sorry for the lack of answer!

I absolutely agree that this should be something we do as soon as possible, especially with the new `run` command. If you are still interested in working on this, I can definitely discuss it in more details here or on the Symfony Slack (https://symfony.com/support)!
