### ISSUE TITLE
Release ?

### ISSUE THREAD

**Issue by lyrixx** [acmephp/acmephp#83]
Hello.

The last release is 1 year old. And I have some issue with it. I would like to try a new version but there are release. Could you release it please ?

Thanks.

**Comment by tgalopin** [comment]
Hello @lyrixx,

Thanks for your message, I am going to work on the project in the next few days to fix issues and do a release.

**Comment by tgalopin** [comment]
Hello @lyrixx,

I just released, but there is still a known issue with expiration of authorization challenges that is very difficult to solve given the position of AcmePHP in the infrastructure: https://github.com/acmephp/acmephp/issues/71. You may still have issues.
