### ISSUE TITLE
Move combined.pem to /private/ subdirectory

### ISSUE THREAD

**Issue by matjon** [acmephp/acmephp#84]
Hello,
File combined.pem contains a private key, yet it is stored in the /certs/ subdirectory. This can be dangerous - someone may publish it in error.

It should be moved to the /private/ subdirectory.

Note: this may break backwards compatiblity so probably it should be created in the /certs/ subdirectory only if it existed there previously.

See:
https://github.com/acmephp/acmephp/blob/09437a74fbe7b1ec345353ba2078e4004000b170/src/Cli/Command/RequestCommand.php#L210
https://github.com/acmephp/acmephp/blob/b727bd3a63f42bbae6f4271d31c0f2cf88cb7dfe/src/Cli/Repository/Repository.php#L275

**Comment by matjon** [comment]
A symlink may be created at certs/$domain/combined.pem that points to private/$domain/combined.pem.

**Comment by tgalopin** [comment]
Thanks for the notice, that's actually a very good point. If you want to do a PR, don't hesitate, otherwise I'll have a look tomorrow. Thanks!
