### ISSUE TITLE
ACME v2 Support

### ISSUE THREAD

**Issue by philipsharp** [acmephp/acmephp#89]
Let's Encrypt has released their staging environment for ACME v2 (including wildcard certificates): https://community.letsencrypt.org/t/staging-endpoint-for-acme-v2/49605

Are there plans to support v2 with this project?

**Comment by tgalopin** [comment]
From what I remeber, @jderusse may want to have a look. I think he'd be happy to have a helping hand if you're interested :) !

**Comment by benjiMediaBowl** [comment]
Any update on this? With LE announcing that wildcard certificates are now available, but only with v2 support it would be nice if acmephp could be used.

**Comment by tgalopin** [comment]
I think this is now merged (https://github.com/acmephp/acmephp/pull/92) and it will be shipped in the next release (no ETA yet, but should be soon).

**Comment by ingluisjimenez** [comment]
Hi @tgalopin @jderusse, I know this issue is closed, but have you considered a tentative date for the next release of Acme PHP?

Also, is there any way that I can help, either testing or contributing to the codebase?

Thanks in advance.
