### ISSUE TITLE
Remove certificates from status?

### ISSUE THREAD

**Issue by programster** [acmephp/acmephp#91]
Hey there,
I've just started using the tool and it's fantastic! Thank you very much. This is going to save me so much time.

### My Problem
I couldn't find any documentation on what commands to run to remove certificates from the tool. E.g. stop them showing up in the output from `acmephp status`. For now, I just want to remove the certificates from my status output, but what if I wanted to go further and revoke them instead? Is that possible?

**Comment by tgalopin** [comment]
Hello @programster,

Thanks for the feedback. For the moment it's not possible unfortunately, but it shouldn't be that difficult to add :) .
